version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-service
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
