name: Python CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
        source $GITHUB_ENV

    - name: Install dependencies
      run: poetry install --with dev --no-root

    # Étape pour exécuter les tests des modèles
    - name: Run Model Tests
      run: poetry run pytest tests/test_models.py

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test  # Cette étape dépend de la réussite des tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape pour construire l'image Docker
      - name: Build Docker image
        run: docker build -t my-api .


